/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apuesta;

import javax.swing.JOptionPane;

/**
 *
 * @author reydi
 */
public class interfazMoneda extends javax.swing.JFrame {

    /**
     * Creates new form interfazMoneda
     */
    public interfazMoneda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        boton1 = new javax.swing.JButton();
        sello = new javax.swing.JLabel();
        cara = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Casa de apuestas ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        boton1.setText("Empezar");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        jPanel1.add(boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, -1));

        sello.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/moneda1.png"))); // NOI18N
        jPanel1.add(sello, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        cara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/moneda2.png"))); // NOI18N
        jPanel1.add(cara, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        String nom = "";
        String s = "";
        int apostar = 0;
        int res = 0;
        sello.setVisible(false);
        cara.setVisible(false);
        nom = JOptionPane.showInputDialog("Ingrese su nombre: ");
        try{
            apostar=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el valor a apostar: "));
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "no es una edad valida");
        }
        int g = 100;
	int c = 0;
                
		while (g > 0 && c < 3) {
                    try{
                 res=Integer.parseInt(JOptionPane.showInputDialog(nom + ", elige 1 que es cara o 2 que es sello"));
            }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "no es un valor valido");
        }
			
			int r = (int) (Math.random() * 2 + 1);
			System.out.println(r);

			if (r == 1 && res == 1) {
				JOptionPane.showMessageDialog(null, "Cara ganaste");
				g = g + apostar * 2;
                                sello.setVisible(false);
                                cara.setVisible(true);
			}

			if (r == 2 && res == 2) {
				JOptionPane.showMessageDialog(null, "Sello ganaste");
				g = g + apostar * 2;
                                sello.setVisible(true);
                                cara.setVisible(false);
			}

			if (r == 2 && res == 1) {
				JOptionPane.showMessageDialog(null, "Sello perdiste");
				g = g - apostar;
                                sello.setVisible(true);
                                cara.setVisible(false);
			}

			if (r == 1 && res == 2) {
				JOptionPane.showMessageDialog(null, "Cara perdiste");
				g = g - apostar;
                                sello.setVisible(true);
			}

			
                        s = JOptionPane.showInputDialog("\"Desea continuar? Si / No");
                        if(s=="Si"||s=="si"){
                            c++;
                        }
                        else{
                            JOptionPane.showMessageDialog(null, nom+" Tu acumulado fue " + g);
                            JOptionPane.showMessageDialog(null, "La cantidad de veces que jugo fue: " + c);
                            System.exit(0);
                        }
		}
    }//GEN-LAST:event_boton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazMoneda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1;
    private javax.swing.JLabel cara;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel sello;
    // End of variables declaration//GEN-END:variables
}
